name: Coverage

on:
  pull_request:
    branches:
      - latest
      - '!dependabot/**'

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build Types
        run: yarn build --buildSingle
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
          test-script: yarn jest
