name: Coverage

on:
  pull_request:
    branches:
      - '*'
      - '!dependabot/**'

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
          test-script: yarn jest
