name: Integration

on:
  push:
    branches:
      - release
      - release-keep-version
      - integration
      - integration-*
      - next
      - next-*
      - latest
  pull_request:
    branches: [latest]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Set npmrc
        run: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Release
        run: yarn release
        env:
          RELEASE_BRANCH: release
          RELEASE_KEEP_VERSION_BRANCH: release-keep-version
          INTEGRATION_BRANCH: integration
          NEXT_BRANCH: next
          STABLE_BRANCH: stable
          LATEST_BRANCH: latest
          PUBLIC_REPO_TOKEN: ${{secrets.PUBLIC_REPO_TOKEN}}
          EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
          GIT_NAME: ${{secrets.GIT_NAME}}
